server:
  port: 8083

spring:
  application:
    name: bot-template-standard
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}

bot:
  id: ${BOT_ID:bot-template-standard}
  displayName: ${BOT_DISPLAY_NAME:Standard Bot Template}
  defaultProfile: ${BOT_PROFILE:MEDIUM}

